name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clean up diskspace
      run: sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
    - uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
        cuda: '12.5.0'
        linux-local-args: '["--toolkit"]'
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    - run: nvcc -V
    - run: df -h
    - uses: actions/checkout@v3   
    - name: Build ffmpeg
      run: cd third_party && bash install_ffmpeg.sh
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build 
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
                 -DWITH_CUDA=ON
                 -DENABLE_FFMPEG_PLUGIN=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: ctest --verbose -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build/src/libllm
    - name: Create release package
      run: zip release-linux-x64-cuda.zip 
             ${{github.workspace}}/build/llm
             ${{github.workspace}}/build/libllmplugincublas.so
             ${{github.workspace}}/build/libllmpluginffmpeg.so
